### ISSUE TITLE
Empresas, organizações e etc que utilizam Markdown em seus sites/aplicações

### ISSUE THREAD

**Issue by LeandraOS** [LeandraOS/GuiaMarkdown#21]
Oooie, seja bem vinde!!! 

O propósito dessa issue é que você escreva um arquivo .md com uma listagem de *empresas, organizações e afins* que renderizam Markdown em seus sites.

> É legal que você adicione links :rocket: 

Bom trabalho :heart_decoration:

**Comment by pserey** [comment]
tou fazendo!!
